### ISSUE TITLE
Put head.php stuff in meta.php

### ISSUE THREAD

**Issue by sandrokeil** [tobiju/bookdown-bootswatch-templates#24]
I think it would be useful to put all the stuff in the _head_ tag to the `meta.php`. Projects can then configure everything they want and easily override/replace some default stuff (e.g. special title tag). What do you think?

**Comment by tobiju** [comment]
I think we need a clean process which copies assets to the book. So we don't need all that inline css and js.

**Comment by sandrokeil** [comment]
Yes, but we can do this in a second step. I think for the most cases individual assets not needed but to manipulate them e.g. another Bootstrap css file, individual titles, open graph tags ...
