### ISSUE TITLE
index.json link in JS must respect root-href

### ISSUE THREAD

**Issue by sandrokeil** [tobiju/bookdown-bootswatch-templates#27]
If you use the templates in a sub folder with the Bookdown `root-href` cli argument, then the search is not working, because of the [hardcoded URL](https://github.com/tobiju/bookdown-bootswatch-templates/blob/develop/templates/script.php#L39).

It must use _https_ and the correct root path/URL.

**Comment by tobiju** [comment]
Not sure how to add https. But root href path will be used now.

**Comment by sandrokeil** [comment]
That's fine. Thanks.
