### ISSUE TITLE
Syntax highlighting renders method doc blocks in one line & adds line breaks

### ISSUE THREAD

**Issue by sandrokeil** [tobiju/bookdown-bootswatch-templates#30]
@tobiju Any idea why method doc blocks `/** ... */` are in one line and empty lines added to the end of the source code (visible in console tools)? See this [page for an example](https://sandrokeil.github.io/interop-config/reference/examples.html).

**Comment by tobiju** [comment]
Should be fixed with commit e6f692fea095879d2ad664bf58b0599983a17649.

**Comment by sandrokeil** [comment]
@tobiju It works like a charm. Will you bring a 1.1.1 release too?

**Comment by tobiju** [comment]
Done!
